// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjX3ZCp-M1YayMk6-oPyl5cCnFe_ZVufM',
    appId: '1:807696680201:web:449841dfdb61ffc7b27fd8',
    messagingSenderId: '807696680201',
    projectId: 'taskmanagemetapp',
    authDomain: 'taskmanagemetapp.firebaseapp.com',
    storageBucket: 'taskmanagemetapp.firebasestorage.app',
    measurementId: 'G-4PVXQCZ40N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRYvt-bUiPHZCzqXwX7rmCOWCAHFNtS9c',
    appId: '1:807696680201:android:a513b32f977213d3b27fd8',
    messagingSenderId: '807696680201',
    projectId: 'taskmanagemetapp',
    storageBucket: 'taskmanagemetapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCS8hSWbYS6friMzYD19qN9XfZApWX_6I',
    appId: '1:807696680201:ios:c9e1cbcb58d87d43b27fd8',
    messagingSenderId: '807696680201',
    projectId: 'taskmanagemetapp',
    storageBucket: 'taskmanagemetapp.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCS8hSWbYS6friMzYD19qN9XfZApWX_6I',
    appId: '1:807696680201:ios:c9e1cbcb58d87d43b27fd8',
    messagingSenderId: '807696680201',
    projectId: 'taskmanagemetapp',
    storageBucket: 'taskmanagemetapp.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjX3ZCp-M1YayMk6-oPyl5cCnFe_ZVufM',
    appId: '1:807696680201:web:2e3b53efc483cd2bb27fd8',
    messagingSenderId: '807696680201',
    projectId: 'taskmanagemetapp',
    authDomain: 'taskmanagemetapp.firebaseapp.com',
    storageBucket: 'taskmanagemetapp.firebasestorage.app',
    measurementId: 'G-4GJ7V8H2MC',
  );
}
